language: ruby
rvm:
- 2.4

script: bundle install && bundle exec jekyll build

exclude: [vendor]

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  local-dir: ./_site
  target-branch: main
  on:
    branch: sources

branches:
  only:
  - sources
